# Generated by Django 4.0.5 on 2022-06-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_curiosidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curiosity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Curiosity',
                'verbose_name_plural': 'Curiosities',
            },
        ),
        migrations.DeleteModel(
            name='Curiosidades',
        ),
    ]
