# Generated by Django 4.0.5 on 2022-06-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_curiosity_delete_curiosidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curiosity',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='curiosity',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
