# Generated by Django 4.0.5 on 2022-07-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
