# Generated by Django 4.0.5 on 2022-07-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
