# Generated by Django 4.0.5 on 2022-07-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.IntegerField(choices=[(1, 'Software'), (2, 'Hardware'), (3, 'Curiosity')]),
        ),
    ]
