# Generated by Django 4.0.5 on 2022-07-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_avatar_delete_userprofile'),
        ('blog', '0010_alter_article_category'),
    ]

    operations = [
    ]
