# Generated by Django 4.0.5 on 2022-07-23 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('H', 'Hardware'), ('S', 'Software'), ('C', 'Curiosidades')], max_length=30),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, max_length=255, null=True)),
                ('receiver', models.ManyToManyField(blank=True, null=True, related_name='receiver_user', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ManyToManyField(blank=True, null=True, related_name='sender_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
