# Generated by Django 4.0.5 on 2022-07-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_comment_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
