# Generated by Django 4.0.5 on 2022-07-13 09:30

import authorization.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authorization.managers.UserManager()),
            ],
        ),
    ]
