# Generated by Django 4.0.5 on 2022-07-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_userprofile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
